### ISSUE TITLE
exception thrown for rename_column migration

### ISSUE THREAD

**Issue by jogaco** [PagerDuty/pt-osc#11]
rename_column migration does not work:

    rename_column :relationships, :from_id, :linked_from_id

```
Unable to execute query on my_project_dev|relationships: CHANGE `from_id` `linked_from_id` int(10) NOT NULL/home/user/.rvm/gems/ruby-2.1.3@my_project/bundler/gems/pt-osc-a81266e748ed/lib/active_record/pt_osc_migration.rb:103:in `execute_sql_for_table'
/home/user/.rvm/gems/ruby-2.1.3@my_project/bundler/gems/pt-osc-a81266e748ed/lib/active_record/pt_osc_migration.rb:89:in `block in migrate_table'
/home/user/.rvm/gems/ruby-2.1.3@my_project/bundler/gems/pt-osc-a81266e748ed/lib/active_record/pt_osc_migration.rb:89:in `each'
/home/user/.rvm/gems/ruby-2.1.3@my_project/bundler/gems/pt-osc-a81266e748ed/lib/active_record/pt_osc_migration.rb:89:in `migrate_table'
/home/user/.rvm/gems/ruby-2.1.3@my_project/bundler/gems/pt-osc-a81266e748ed/lib/active_record/pt_osc_migration.rb:80:in `block in execute_pt_osc'
/home/user/.rvm/gems/ruby-2.1.3@my_project/bundler/gems/pt-osc-a81266e748ed/lib/active_record/pt_osc_migration.rb:80:in `each'
/home/user/.rvm/gems/ruby-2.1.3@my_project/bundler/gems/pt-osc-a81266e748ed/lib/active_record/pt_osc_migration.rb:80:in `execute_pt_osc'
/home/user/.rvm/gems/ruby-2.1.3@my_project/bundler/gems/pt-osc-a81266e748ed/lib/active_record/pt_osc_migration.rb:59:in `block (2 levels) in migrate'
/home/user/.rvm/gems/ruby-2.1.3@my_project/bundler/gems/pt-osc-a81266e748ed/lib/active_record/pt_osc_migration.rb:59:in `block in migrate'
```

Instead, a plain and ugly execute_sql does:

    execute 'alter table relationships change from_id linked_from_id int(10) NOT NULL'

**Comment by steverice** [comment]
You're having this issue because of `pt-online-schema-change`'s default [`--check-alter` behavior](http://www.percona.com/doc/percona-toolkit/2.1/pt-online-schema-change.html#cmdoption-pt-online-schema-change--[no]check-alter) to warn against possibly dangerous statements.

A fix is in the works to allow overriding this check.

**Comment by jogaco** [comment]
Great!

**Comment by steverice** [comment]
The latest release [v0.2.0](https://github.com/steverice/pt-osc/releases/tag/v0.2.0) provides the ability to set `check-alter: false` in your config which will allow you to run the migration.

Without it, you'll get a message like this:
```
Altering `relationships`...
--alter appears to rename these columns:
  from_id to linked_from_id
The tool should handle this correctly, but you should test it first because if it fails the renamed columns' data will be lost!  Specify --no-check-alter to disable this check and perform the --alter.
```

Heed this warning and set the flag to `false` only if you've tested the migration successfully in a non-production environment.
